sudo: required

services:
    - docker
    
before_install:
    - docker build -t nikolac/docker-react - f Dockerfile .
    
script: 
    - docker run nikolac/docker-react npm run test -- --coverage
  
deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-central-1-891377230472"
    bucket_path: "docker"
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
    
    